### ISSUE TITLE
JLAB v3.0.7

### ISSUE THREAD

**Issue by BBassi** [bloomberg/ipydatagrid#193]
<img width="877" alt="Screenshot 2021-02-26 at 11 03 35" src="https://user-images.githubusercontent.com/25634627/109292556-74e02580-7822-11eb-9f54-de9c2eb46626.png">

**Comment by jasongrout** [comment]
You do not need to install anything with `labextension install` to get this working in JuptyerLab 3.0

A simple `pip install ipydatagrid` should be sufficient if you have ipywidgets 7.6.

The readme is being updated in #189

**Comment by BBassi** [comment]
Thanks!

Also get this error from some of the exmaples:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e2f4d41f6129> in <module>
      1 import pandas as pd
----> 2 from ipydatagrid import DataGrid, TextRenderer, VegaExpr
      3 
      4 df = pd.DataFrame(
      5     {

ImportError: cannot import name 'TextRenderer' from 'ipydatagrid' (/srv/conda/envs/notebook/lib/python3.7/site-packages/ipydatagrid/__init__.py)

**Comment by ibdafna** [comment]
Fixed in #198

**Comment by ibdafna** [comment]
Released a fix! `pip install ipydatagrid==1.0.1` should get this working now.
